//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMA_DESK.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NMAEntities_ : DbContext
    {
        public NMAEntities_()
            : base("name=NMAEntities_")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accidente> accidente { get; set; }
        public virtual DbSet<asesoria> asesoria { get; set; }
        public virtual DbSet<atraso> atraso { get; set; }
        public virtual DbSet<capacitacion> capacitacion { get; set; }
        public virtual DbSet<caso> caso { get; set; }
        public virtual DbSet<checklist> checklist { get; set; }
        public virtual DbSet<contrato> contrato { get; set; }
        public virtual DbSet<detalle_factura> detalle_factura { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<multa> multa { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo_multa> tipo_multa { get; set; }
        public virtual DbSet<tipo_usuario> tipo_usuario { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<visita> visita { get; set; }
    }
}
