//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMA_DESK.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class capacitacion
    {
        public int id_capacitacion { get; set; }
        public Nullable<System.DateTime> fec_capacit { get; set; }
        public string tema_capacit { get; set; }
        public string material_capacit { get; set; }
        public string list_asistente { get; set; }
        public string estad_capacit { get; set; }
        public string tipo_capaci { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
