//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMA_DESK.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caso
    {
        public int id_caso { get; set; }
        public string correspondencia { get; set; }
        public string documentos { get; set; }
        public string obs_profesional { get; set; }
        public byte[] conver_grabada { get; set; }
        public string estado_caso { get; set; }
        public string tipo_caso { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
