//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMA_DESK.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklist
    {
        public int id_checklist { get; set; }
        public string nom_checklist { get; set; }
        public string obs_checklist { get; set; }
        public byte[] document_rev { get; set; }
        public string nombre_doc { get; set; }
        public string extension_doc { get; set; }
        public Nullable<bool> estado_checklist { get; set; }
        public Nullable<int> id_visita { get; set; }
    
        public virtual visita visita { get; set; }
    }
}
