//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMA_DESK.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contrato()
        {
            this.factura = new HashSet<factura>();
        }
    
        public int id_contrato { get; set; }
        public Nullable<System.DateTime> fec_inicio_cont { get; set; }
        public Nullable<System.DateTime> fec_termino_cont { get; set; }
        public string estado_contrato { get; set; }
        public byte[] contrado_firmado { get; set; }
        public string nombre_contrato { get; set; }
        public Nullable<int> valor_contrato { get; set; }
        public Nullable<int> id_empresa { get; set; }
    
        public virtual empresa empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
    }
}
