//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMA_DESK.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_factura
    {
        public int id_detalle_factura { get; set; }
        public Nullable<int> valor_bruto { get; set; }
        public Nullable<int> valor_neto { get; set; }
        public Nullable<int> id_factura { get; set; }
    
        public virtual factura factura { get; set; }
    }
}
