//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMA_DESK.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresa()
        {
            this.contrato = new HashSet<contrato>();
            this.usuario = new HashSet<usuario>();
        }
    
        public int id_empresa { get; set; }
        public string rut_empresa { get; set; }
        public string nom_empresa { get; set; }
        public string estado_empresa { get; set; }
        public string tipo_empresa { get; set; }
        public Nullable<int> cant_trabajadores { get; set; }
        public Nullable<int> telefono_emp { get; set; }
        public string correo_emp { get; set; }
        public string region_empresa { get; set; }
        public string comuna_emp { get; set; }
        public string direccion_emp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contrato> contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
