//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMA_DESK.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.detalle_factura = new HashSet<detalle_factura>();
        }
    
        public int id_factura { get; set; }
        public Nullable<System.DateTime> fec_factura { get; set; }
        public Nullable<System.DateTime> fec_vencimiento { get; set; }
        public Nullable<bool> estado_pago { get; set; }
        public Nullable<int> visita_extra { get; set; }
        public Nullable<int> capaci_extra { get; set; }
        public Nullable<int> aseso_extra { get; set; }
        public Nullable<int> total_factura { get; set; }
        public Nullable<int> id_contrato { get; set; }
    
        public virtual contrato contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura> detalle_factura { get; set; }
    }
}
