//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMA_DESK.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class multa
    {
        public int id_multa { get; set; }
        public string multa_ent_fisc { get; set; }
        public string descrip_multa { get; set; }
        public Nullable<int> valor_multa { get; set; }
        public string estado_multa { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_tipo_multa { get; set; }
    
        public virtual tipo_multa tipo_multa { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
