//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMA_DESK.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visita()
        {
            this.checklist = new HashSet<checklist>();
        }
    
        public int id_visita { get; set; }
        public Nullable<System.DateTime> fec_visita { get; set; }
        public string direcc_visita { get; set; }
        public Nullable<System.DateTime> hor_visita { get; set; }
        public string estado_visita { get; set; }
        public string tipo_visita { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_profesional { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<checklist> checklist { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
